# Les joueurs peuvent blesser et tuer les autres joueurs
PVP=true

# PVP is logged to admin chat
PVPLogToolChat=true

# PVP is logged to file
PVPLogToolFile=true

# Le temps du jeu s'arrête lorsqu'il n'y a aucun joueur connecté
PauseEmpty=true

# Autorise ou non l'utilisation du chat global /all.
GlobalChat=true

ChatStreams=s,r,a,w,y,sh,f,all

# Les clients peuvent se connecter sans avoir au préalable un compte inscrit en liste blanche. Si réglé sur 'False', les administrateurs devront créer manuellement les noms d'utilisateur et mots de passe associés.
Open=true

# Le premier message que verront les joueurs dans la fenêtre de chat. Ceci sera affiché directement après la connexion d'un joueur. Vous pouvez utiliser le code couleur RGB afin de colorer votre message. Vous pouvez également utiliser <LINE> afin de revenir à la ligne. Si vous utilisez par exemple : <RGB:1.0.0> Ce message apparaîtra en rouge !
ServerWelcomeMessage=Welcome to Project Zomboid Multiplayer! <LINE> <LINE> To interact with the Chat panel: press Tab, T, or Enter. <LINE> <LINE> The Tab key will change the target stream of the message. <LINE> <LINE> Global Streams: /all <LINE> Local Streams: /say, /yell <LINE> Special Steams: /whisper, /safehouse, /faction. <LINE> <LINE> Press the Up arrow to cycle through your message history. Click the Gear icon to customize chat. <LINE> <LINE> Happy surviving!

ServerImageLoginScreen=

ServerImageLoadingScreen=

ServerImageIcon=

# Ajoute les noms d'utilisateurs inconnus à la liste blanche lorsque des joueurs se connectent. Pour les serveurs ouverts, avec Open
AutoCreateUserInWhiteList=false

# Affiche le nom d'utilisateur au-dessus de la tête des joueurs en jeu.
DisplayUserName=true

# Affiche le nom et prénom (du personnage) des joueurs au dessus de leur tête.
ShowFirstAndLastName=false

UsernameDisguises=false

HideDisguisedUserName=false

SwitchZombiesOwnershipEachUpdate=false

# Oblige tout nouveau joueur à apparaître à ces coordonnées x,y,z. Trouvez les coordonnées souhaitez sur https://map.six.ph/. (Ignoré si 0,0,0)
SpawnPoint=0,0,0

# Les joueur peuvent activer et désactiver le PvP individuellement. Un joueur peut en blesser un autre, seulement si l'un des deux a le PvP activé, comme le montrent le crâne et les os croisés non obscurcis en bas à gauche de l'écran. Lorsque SafetySystem=false, les joueurs peuvent se blesser à n'importe quel moment même si aucun d'entre eux n'a activé le PvP.
SafetySystem=true

# Affiche une tête de mort au-dessus des joueurs qui ont activé le mode PVP
ShowSafety=true

# Le temps que prend l'activation / la désactivation du mode PVP par un joueur Minimum=0 Maximum=1000 Par défaut=2
SafetyToggleTimer=2

# Délai avant qu'un joueur entre ou ne sorte de nouveau du mode PVP juste après l'avoir déjà fait Minimum=0 Maximum=1000 Par défaut=3
SafetyCooldownTimer=3

# Minimum=0 Maximum=60 Par défaut=60
SafetyDisconnectDelay=60

# Le type d'objets avec lesquels apparaîtront les nouveaux joueurs. Séparez les différents objets à l'aide d'une virgule. Exemple : Base.Axe,Base.Bag_BigHikingBag
SpawnItems=

# Port par défaut pour les données du joueur. S'il s'agit d'UDP, c'est celui-ci des deux qui sera utilisé. Minimum=0 Maximum=65535 Par défaut=16261
DefaultPort=16261

# Minimum=0 Maximum=65535 Par défaut=16262
UDPPort=16262

# Le Reset ID détermine si le serveur a subi un Soft Reset (Réinitialisation partielle). Si ce numéro correspond au client, le client doit créer un nouveau personnage. C'est utilisé en conjonction avec PlayerServerID. Il est fortement recommandé de sauvegarder ces IDs quelque part. Minimum=0 Maximum=2147483647 Par défaut=192623045
ResetID=7994878

# Entrez l'ID de chargement du Mod ici. L'info est à récupérer sur \Steam\steamapps\workshop\modID\mods\modName\info.txt
Mods=

# Entrez le nom du dossier du Mod comme trouvé sur \Steam\steamapps\workshop\modID\mods\modName\media\maps\
Map=Muldraugh, KY

# Éjecte les clients dont les fichiers ne correspondent pas à ceux du serveur.
DoLuaChecksum=true

DenyLoginOnOverloadedServer=true

# Affiche le serveur dans l'écran de recherche de serveur en jeu. (Note : Les serveurs Steam-activé seront toujours visibles dans la recherche de serveur via Steam)
Public=false

# Le nom du serveur affiché dans l'écran de recherche en jeu, et si c'est possible, dans le navigateur des serveurs Steam
PublicName=My PZ Server

# Description affichée dans l'écran de recherche de serveurs publics en jeu. Taper   créera une nouvelle ligne dans votre description
PublicDescription=

# Nombre maximum de joueurs pouvant se connecter au serveur simultanément. Ceci exclut les admins.
# AVERTISSEMENT : un nombre de joueurs supérieur à 32 entraînera potentiellement une mauvaise diffusion de la carte et des désynchronisations. Merci d'y aller prudemment. Minimum=1 Maximum=100 Par défaut=32
MaxPlayers=32

# La limite de ping, en millisecondes, avant que le joueur soit expulsé du serveur. (Régler sur 0 pour désactiver) Minimum=0 Maximum=2147483647 Par défaut=0
PingLimit=0

# Items will not respawn in buildings that players have claimed as a safehouse
SafehousePreventsLootRespawn=true

# Retire les comptes de joueurs de la liste blanche après leur mort. Ceci empêchera de créer un nouveau personnage après une mort en jeu sur les serveurs Open
DropOffWhiteListAfterDeath=false

# Désactive toute forme de feu sur votre serveur, excepté les feux de camp.
NoFire=false

# Si activé, un message sera affiché dans le chat à chaque fois qu'un joueur meurt.
AnnounceDeath=false

# If checked, every time an animal dies a global message will be displayed in the chat
AnnounceAnimalDeath=false

# Les parties chargées de la carte sont sauvegardées après que ce nombre de minutes RÉELLES soit écoulé. (La carte est habituellement sauvegardée seulement après que les clients aient quitté une zone chargée) Minimum=0 Maximum=2147483647 Par défaut=0
SaveWorldEveryMinutes=0

# Les admins et les autres joueurs peuvent revendiquer un abri
PlayerSafehouse=false

# Seuls les admins peuvent revendiquer des abris.
AdminSafehouse=false

# Autorise les joueurs qui ne font pas partie de cet abri à y entrer
SafehouseAllowTrepass=true

# Permet au feu d'endommager les abris
SafehouseAllowFire=true

# Autorise les joueurs qui ne font pas partie de cet abri à y prendre des objets
SafehouseAllowLoot=true

# Les joueurs réapparaissent dans un abri dont ils étaient membres avant leur mort
SafehouseAllowRespawn=false

# Les joueurs doivent avoir survécu durant ce nombre de jours en jeu avant de pouvoir revendiquer un abri Minimum=0 Maximum=2147483647 Par défaut=0
SafehouseDaySurvivedToClaim=0

# Les joueurs sont automatiquement retirés d'un abri qu'ils n'ont pas visité durant ce nombre d'heures RÉELLES Minimum=0 Maximum=2147483647 Par défaut=144
SafeHouseRemovalTime=144

# Définis si les joueurs sont autorisés ou non à revendiquer des bâtiments non résidentiels (magasins, etc...).
SafehouseAllowNonResidential=false

SafehouseDisableDisguises=true

# Minimum=0 Maximum=2147483647 Par défaut=20000
MaxSafezoneSize=20000

# Autorise les joueurs à détruire les objets à l'aide d'une masse.
AllowDestructionBySledgehammer=true

# Autorise les joueurs à détruire des objets à l'aide d'une masse uniquement dans leur abri (AllowDestructionBySledgehammer doit être activé pour fonctionner).
SledgehammerOnlyInSafehouse=false

War=true

# Time in seconds before the war starts. Minimum=60 Maximum=2147483647 Par défaut=600
WarStartDelay=600

# War duration in seconds. Minimum=60 Maximum=2147483647 Par défaut=3600
WarDuration=3600

# Safehouse hit points limit. Minimum=0 Maximum=2147483647 Par défaut=3
WarSafehouseHitPoints=3

# ServerPlayerID détermine si un personnage vient d'un autre serveur ou d'une partie solo. Cette valeur peut être modifiée lors d'un Soft Reset (réinitialisation partielle). Si ce nombre correspond au client, le client devra créer un nouveau personnage. Ceci est utilisé en conjonction avec ResetID. Il est fortement recommandé de conserver ces IDs quelque part.
ServerPlayerID=

# Port pour le RCON (Remote Console - Console à distance) Minimum=0 Maximum=65535 Par défaut=27015
RCONPort=27015

# Mot de passe RCON (Favorisiez un mot de passe complexe)
RCONPassword=

# Permet l'intégration du chat textuel global dans un canal Discord
DiscordEnable=false

# Token d'accès au bot Discord
DiscordToken=

# The Discord chat channel name
DiscordChatChannel=

# The Discord logs channel name
DiscordLogChannel=

# The Discord commands channel name
DiscordCommandChannel=

# The Slack incoming webhook URL
WebhookAddress=

# Les clients doivent connaître ce mot de passer pour rejoindre le serveur. (Ignoré lors de l'hébergement d'une partie via "Héberger")
Password=

# Limite le nombre de comptes différents qu'un même utilisateur Steam peut créer sur ce serveur. Ignoré lors de l'hébergement d'une partie. Minimum=0 Maximum=2147483647 Par défaut=0
MaxAccountsPerUser=0

# Autoriser les joueurs co-op/écran partagé
AllowCoop=true

# Les joueurs sont autorisés à dormir lorsque leur survivant est essouflé/épuisé, mais ils n'ont pas BESOIN de dormir
SleepAllowed=false

# Les joueurs ressentent la fatigue et ont besoin de dormir. (Ignoré si SleepAllowed est désactivé)
SleepNeeded=false

# WIP: Activating this setting may cause visual desynchronization of player positions.
KnockedDownAllowed=false

SneakModeHideFromOtherPlayers=true

UltraSpeedDoesnotAffectToAnimals=false

# Liste les IDs de mod du Workshop que le serveur doit télécharger. Séparés par un point-virgule. Exemple : WorkshopItems=514427485;513111049
WorkshopItems=

# Montre les noms d'utilisateurs Steam et leurs avatars dans la liste des joueurs. Peut être réglé sur 'True' (visible par tout le monde), 'False' (visible par personne) ou 'Admin' (visible par les admins uniquement)
SteamScoreboard=false

# Utiliser le système anti-triche Steam (VAC = Valve Anti-Cheat).
SteamVAC=true

# Tente de configurer une passerelle internet UPnP afin de configurer automatiquement les règles de redirection de port. Le serveur reprendra les valeurs par défaut si ceci échoue
UPnP=true

# Si activé, le chat vocal sera disponible en jeu.
VoiceEnable=true

# Distance minimale à laquelle le chat vocal (VOIP) peut être entendu. Minimum=0,00 Maximum=100000,00 Par défaut=10,00
VoiceMinDistance=10.0

# Distance maximale à laquelle le chat vocal (VOIP) peut être entendu. Minimum=0,00 Maximum=100000,00 Par défaut=100,00
VoiceMaxDistance=100.0

# Son directionnel pour le chat vocal (VOIP)
Voice3D=true

# Minimum=10,00 Maximum=150,00 Par défaut=70,00
SpeedLimit=80.0

LoginQueueEnabled=false

# Minimum=20 Maximum=1200 Par défaut=60
LoginQueueConnectTimeout=60

# Fixe l'IP sur laquelle le serveur émet. Destiné aux configurations de réseaux avec IP multiples, comme les batteries de serveurs
server_browser_announced_ip=

# Les joueurs peuvent réapparaître à l'endroit de leur mort.
PlayerRespawnWithSelf=false

# Dans une partie en écran partagé/Remote Play, les joueurs peuvent réapparaître à l'emplacement de l'autre joueur.
PlayerRespawnWithOther=true

# Détermine à quelle vitesse le temps s'écoule lorsque les joueurs dorment. La valeur multiplie la vitesse du temps qui passe durant le sommeil. Minimum=1,00 Maximum=100,00 Par défaut=40,00
FastForwardMultiplier=40.0

# Chaque abri fonctionnera comme une maison normale si un joueur y habitant est connecté (seront alors sécurisés lorsque les joueurs seront hors-ligne).
DisableSafehouseWhenPlayerConnected=false

# Si activé, permet aux joueurs de créer des factions.
Faction=true

# Nombre de jour(s) de survie nécessaire(s) en jeu, avant de pouvoir créer une faction. Minimum=0 Maximum=2147483647 Par défaut=0
FactionDaySurvivedToCreate=0

# Nombre de membres recrutés requis avant que le créateur puisse attribuer un tag à la faction Minimum=1 Maximum=2147483647 Par défaut=1
FactionPlayersRequiredForTag=1

# Désactive les transmissions radio des joueurs de tous les niveaux d'accès.
DisableRadioStaff=false

# Désactive les transmissions radio des joueurs de niveau d'accès Admin.
DisableRadioAdmin=true

# Désactive les transmissions radio des joueurs de niveau d'accès GM.
DisableRadioGM=true

# Désactive les transmissions radio des joueurs de niveau d'accès Overseer.
DisableRadioOverseer=false

# Désactive les transmissions radio des joueurs de niveau d'accès Modérateur.
DisableRadioModerator=false

# Désactive les transmissions radio des joueurs invisibles.
DisableRadioInvisible=true

# Liste de commandes, séparées par des points-virgules, qui ne seront pas écrites dans le log serveur cmd.txt.  -vehicle. * signifie exclure toutes les commandes des véhicules.  +vehicle.installPart signifie inclure cette commande.
ClientCommandFilter=-vehicle.*;+vehicle.damageWindow;+vehicle.fixPart;+vehicle.installPart;+vehicle.uninstallPart

# Liste d'actions séparées par des points-virgules qui seront écrites dans les logs du serveur ClientActionLogs.txt.
ClientActionLogs=ISEnterVehicle;ISExitVehicle;ISTakeEngineParts;

# Dans le fichier PerkLog.txt, sont retracés les changements dans les niveaux de compétence des joueurs
PerkLogs=true

# Nombre maximum d'objets pouvant être mis dans un contenant. Zéro signifie aucune limite. (SVP NOTEZ QUE : Ceci inclus les petits objets individuels tels que les clous. Une limite de 50 signifiera que 50 clous pourront être stockés.) Minimum=0 Maximum=9000 Par défaut=0
ItemNumbersLimitPerContainer=0

# Nombre de jours avant la disparition des giclures de sang. 
#  Elles seront supprimées au chargement des chunks de la carte. 
#  Zéro signifie qu'elles ne disparaitront jamais Minimum=0 Maximum=365 Par défaut=0
BloodSplatLifespanDays=0

# Autoriser ou non l'utilisation de caractères non-ASCII (cyrillique, etc ...) pour le nom d'utilisateur.
AllowNonAsciiUsername=false

BanKickGlobalSound=true

# Si activé, quand HoursForCorpseRemoval s'activera, cela affectera également les cadavres de joueurs qui disparaitront du sol.
RemovePlayerCorpsesOnCorpseRemoval=false

# Si activé, les joueurs pourront utiliser le bouton 'Tout supprimer' dans les poubelles.
TrashDeleteAll=true

# Si activé, le joueur peut riposter lorsqu'il est attaqué par un autre joueur.
PVPMeleeWhileHitReaction=false

# Si activé, les joueurs devront passer la souris sur quelqu'un afin d'afficher leur nom.
MouseOverToSeeDisplayName=false

# Si activé, masque automatiquement les joueurs que vous ne pouvez pas voir (comme les zombies).
HidePlayersBehindYou=false

# Dégats supplémentaires pour les attaques de mêlée en PVP. Minimum=0,00 Maximum=500,00 Par défaut=30,00
PVPMeleeDamageModifier=30.0

# Dégats supplémentaires pour les attaques à distance en PVP. Minimum=0,00 Maximum=500,00 Par défaut=50,00
PVPFirearmDamageModifier=50.0

# Modifie la portée d'attraction des zombies par les voitures. Diminuer la valeur peut aider contre les lags serveur. Minimum=0,00 Maximum=10,00 Par défaut=0,50
CarEngineAttractionModifier=0.5

# Détermine si les joueurs peuvent se bousculer (se faire tomber) lorsqu'ils courent en se rentrant dedans.
PlayerBumpPlayer=false

# Définit l'affichage des autres joueurs sur la carte en jeu. 1=Personne 2=Amis uniquement 3=Tout le monde Minimum=1 Maximum=3 Par défaut=1
MapRemotePlayerVisibility=1

# Minimum=1 Maximum=300 Par défaut=5
BackupsCount=5

BackupsOnStart=true

BackupsOnVersionChange=true

# Minimum=0 Maximum=1500 Par défaut=0
BackupsPeriod=0

# Disables vehicle towing
DisableVehicleTowing=false

# Disables trailer towing
DisableTrailerTowing=false

# Disables burnt vehicle towing
DisableBurntTowing=false

# Path to the file with the list of words to be prohibited. Each word must be on a separate line
BadWordListFile=

# Path to the file with the list of words that should be allowed, even if they contain bad word. Each word should be on a separate line.
GoodWordListFile=

# What to do with the sender of a bad word in the chat: 1 - ban, 2 - kick, 3 - record the violation in the database, 4 - mute
BadWordPolicy=3

# The symbol or piece of text that will replace the bad word
BadWordReplacement=[HIDDEN]

# Disables safety system anti-cheat protection.
AntiCheatSafety=4

AntiCheatMovement=4

# Disables character hit anti-cheat protection.
AntiCheatHit=4

# Disables packet checks anti-cheat protection.
AntiCheatPacket=4

# Disables player permissions anti-cheat protection.
AntiCheatPermission=4

# Disables player XP anti-cheat protection.
AntiCheatXP=4

# Disables fire checks anti-cheat protection.
AntiCheatFire=4

# Disables safehouse anti-cheat protection.
AntiCheatSafeHouse=4

# Disables recipe checks anti-cheat protection.
AntiCheatRecipe=4

AntiCheatPlayer=4

# Disables checksum anti-cheat protection.
AntiCheatChecksum=4

# Disables item checks anti-cheat protection.
AntiCheatItem=4

AntiCheatServerCustomization=4

# Sets the multiplayer update period in seconds. Statistics is disabled if value is 0. Minimum=0 Maximum=10 Par défaut=1
MultiplayerStatisticsPeriod=1

# Disables scoreboard.
DisableScoreboard=false

# Hides admins in the player list.
HideAdminsInPlayerList=false

# The worldgen seed used to generate the world.
# If you want to change this, put a new value in and delete map_worldgen.bin in your save directory.
Seed=

UsePhysicsHitReaction=false

# Minimum=64 Maximum=1024 Par défaut=200
ChatMessageCharacterLimit=200

# Minimum=1 Maximum=30 Par défaut=3
ChatMessageSlowModeTime=3